data:
  attr_dir: /research/hal-afsharim/minimal_cbm/data/cub12
  dataset: CUB200
  imgs_dir: /research/hal-afsharim/minimal_cbm/data/cub12/CUB_200_2011/images
  modify_pkls: true
  n_groups_concepts: 12
  pkls_dir: /research/hal-afsharim/minimal_cbm/data/cub12/CUB_processed/base
model:
  beta: 0.1
  encoder:
    arch: inception_v3
    hidden_dim: 1024
    pretrained: true
  gamma: 0.1
  hidden_dims_c:
  - 3
  hidden_dims_y: 256
  hidden_dims_z: null
  model_type: mcbm
  var_z: 1
training:
  batch_size: 128
  n_epochs: 2
  optimizer:
    base_batch_size: 64
    base_lr: 0.01
    batch_size: 128
    momentum: 0.9
    optimizer: SGD
    weight_decay: 4.0e-05
  save_epochs: 2
  scheduler:
    gamma: 0.1
    scheduler: StepLR
    step_size: 100
